start: 9
stop: 23
period: 365
recipe: 
 tomato: 50.0
 pumpkin: 50.0
 salad: 30.0
 oil: 10.0
 duck: 70.0
 cheese: 40.0
morning: 0.15
afternoon: 0.6
evening: 0.25
amount:
    90.0: "20-30"
    5.0: "30-40"
    3.0: "40-50"
    2.0: "50-60"